name: portfolio
description: Binh's Portfolio
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  url_launcher: ^6.3.1
  visibility_detector: ^0.4.0+2
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/Lato/Lato-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Lato/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato/Lato-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Lato/Lato-Regular.ttf
        - asset: assets/fonts/Lato/Lato-Italic.ttf
          style: italic
        - asset: assets/fonts/Lato/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato/Lato-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Lato/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/Lato/Lato-ThinItalic.ttf
          weight: 100
          style: italic
    - family: Fira Code
      fonts:
        - asset: assets/fonts/FiraCode/FiraCode-VF.ttf
